---
title: 'Analysis for age range 30-50 years with BMXWAIST, HEI'
author: "Aritra Ghosal"
date: "2/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}

library("optimParallel")
library("tidyverse")
library("survey")
library("fda.usc")
library("sandwich")
library("compiler")

```

```{r, warning= FALSE}
# Aritra's library for R operations
#setwd("~/Documents/FSI/Application /alex/FSI_NHANES/Archive_PLFSI")
# Aritra's library for R operations in RAS server
setwd("~/MATLAB/Archive_PLFSI")

# Use your own directory

#setwd("C:/Users/Admin/Downloads/Archive_rmd_65")

# read the dataset
datos= read.csv("datosalex(1).csv")
indices= round(seq(188,687, length=500))

colnames(datos)[indices]= paste("X", 1:500, sep="")
datos= datos[, c(1:187, indices)]
datos<- subset(datos, datos$RIDAGEYR.x >= 30 & datos$RIDAGEYR.x <= 50)  # subset data for age 30-50 years
datosfda= datos[,188:687]
datosfda= as.matrix(datosfda)
datosfda[which(datosfda>280)]= datosfda[which(datosfda>280)-1]+0.5
datos[,188:687]= datosfda

tt= seq(0,1,length=500)
objetofda= fdata(datosfda,argvals = tt)

#relevel(data_analysis_svy$variables$RIDRETH3,3) 

si_vars <- c("BMXBMI","RIDAGEYR.y")  # covariates for Single Index part
linear_vars<- c("RIAGENDR","RIDRETH3","BMXWAIST","HEI")  # covariates for Linear part
linear_vars_numerical <- c("BMXWAIST","HEI")  # numeric covariates for Linear part
linear_vars_categorical <- c("RIAGENDR","RIDRETH3")  # categorical covariates for Linear part


# the survey variables
datosx <- cbind.data.frame(scale(datos[,si_vars]), datos[,linear_vars_categorical], scale(datos[,linear_vars_numerical]), survey_wt= datos[,"wtmec4yr_adj_norm"],survey_id=datos[,"SDMVPSU"], survey_strata= datos[,"SDMVSTRA"])
datosx$RIAGENDR<- as.factor(datosx$RIAGENDR)
datosx$RIDRETH3<- as.factor(datosx$RIDRETH3)
datosx$survey_strara<- as.factor(datosx$survey_strata)
datosx$survey_id<- as.factor(datosx$survey_id)

# obtain the global Frechet model

## compute the regression formula for the model
  formula<- paste(paste(linear_vars,collapse="+"), paste(paste(si_vars),collapse="+"),sep="+")
  data_temp <- cbind.data.frame(datosx, datosfda)
  data_analysis_svy <- svydesign(id= ~survey_id, strata = ~survey_strata, 
                                 weights= ~survey_wt,data = data_temp,nest = TRUE)
  
  source("survey2wassersteinmodel.R", local =knitr::knit_global())
  res<- survey2wassersteinmodel(formula=formula, data_analysis_svy, objetofda=objetofda)
  # obtain R-squared 
  res$r2

# Frechet R-squared of the GF model
source("adj_fr_r2.R", local = knitr::knit_global())
frsq<- adj_fr_r2(qin=datosfda, qpred=res$predicciones, tt=tt, q=nrow(res$betaj))
frsq$Frechet_R2

# Adjusted Frechet R-squared of GF model
frsq$Frechet_Adj_R2

source("PLFSI_model.R", local = knitr::knit_global())
lmod<- PLFSI_model(si_vars = si_vars, linear_vars = linear_vars, datosfda = datosfda, tt =tt, 
                   nsp = 4, L = 0, etaStart = NULL, sp=4, dfs=9, datosx= datosx)

# report the Frechet R^2
lmod$Frechet.R2

# report the Adjusted Frechet R^2
lmod$Adj.Frechet.R2

# report the R^2
lmod$R2

# estimate of index parameter
lmod$thetaHat

# To check if all points converged
lmod$converge

# obtain the residuals with patient id
res_id<- cbind.data.frame(SEQN =datos$SEQN, lmod$residuals)
colnames(res_id)<- c("SEQN", paste("X", c(1:ncol(lmod$residuals)), sep = ""))

# save the residuals for further analysis
write.csv(res_id, "Output_Age30to50_BMXWAIST_HEI_noTAC_residuals.csv") 

# to plot of the beta estimates
betas  <- lmod$betaj
rnames <- rownames(betas)
beta_ucl<- lmod$beta_ucl
beta_lcl<- lmod$beta_lcl

write.csv(betas, "Output_Age30to50_BMXWAIST_HEI_noTAC_betas.csv" )
write.csv(rnames, "Output_Age30to50_BMXWAIST_HEI_noTAC_rnames.csv")
write.csv(lmod$beta_ucl, "Output_Age30to50_BMXWAIST_HEI_noTAC_betas_UCL.csv" )
write.csv(lmod$beta_lcl, "Output_Age30to50_BMXWAIST_HEI_noTAC_betas_LCL.csv" )

```


```{r, echo=FALSE, eval=FALSE}

#par(mfrow= c(2,3))
#plot(tt,betas[1,], xlab= "Quantile,t", ylab="Q(t)", main="Intercept" , ylim=c(-15.02, 150))
#plot(tt,betas[2,], xlab= "Quantile,t", ylab="Q(t)" , main="Gender: Female",ylim=c(-15.02, 150))
#plot(tt,betas[3,], xlab= "Quantile,t", ylab="Q(t)", main="Other Hispanic",ylim=c(-15.02, 150))
#plot(tt,betas[4,], xlab= "Quantile,t", ylab="Q(t)",main="non-Hispanic White", ylim=c(-15.02, 150))
#plot(tt,betas[5,], xlab= "Quantile,t", ylab="Q(t)",main="non-Hispanic black",ylim=c(-15.02, 150))
#plot(tt,betas[6,], xlab= "Quantile,t", ylab="Q(t)",main="non-Hispanic Asian",ylim=c(-15.02, 150))
#plot(tt,betas[7,], xlab= "Quantile,t", ylab="Q(t)",main="non-Hispanic multiracial",ylim=c(-15.02, 150) )

#plot(tt,betas[8,],main= rnames[8], xlab= "Quantile,t", ylab="Q(t)" ,ylim=c(-15.02, 150))
#plot(tt,betas[9,],main= rnames[9], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )

#plot(tt,betas[10,],main= rnames[10], xlab= "Quantile,t", ylab="Q(t)" ,ylim=c(-15.02, 150))
#plot(tt,betas[11,],main= rnames[11], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )
#plot(tt,betas[12,],main= rnames[12], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )

#plot(tt,betas[13,],main= rnames[13], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )
#plot(tt,betas[14,],main= rnames[14], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )
#plot(tt,betas[15,],main= rnames[15], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )
#plot(tt,betas[16,],main= rnames[16], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )

#plot(tt,betas[17,],main= rnames[17], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )
#plot(tt,betas[18,],main= rnames[18], xlab= "Quantile,t", ylab="Q(t)",ylim=c(-15.02, 150) )


par(mfrow= c(2,3))
plot(tt,betas[1,], xlab= "Quantile,t", ylab="beta(t)", main="Intercept", cex=0.1)
points(tt, beta_lcl[1,], col="red", cex=0.1)
points(tt, beta_ucl[1,], col="green", cex=0.1)
abline(h=0,lty=3)

plot(tt,betas[2,], xlab= "Quantile,t", ylab="beta(t)" , main="Gender: Female", cex=0.1)
points(tt, beta_lcl[2,], col="red", cex=0.1)
points(tt, beta_ucl[2,], col="green", cex=0.1)
abline(h=0,lty=3)

plot(tt,betas[3,], xlab= "Quantile,t", ylab="beta(t)", main="Other Hispanic",cex=0.1)
points(tt, beta_lcl[3,], col="red", cex=0.1)
points(tt, beta_ucl[3,], col="green", cex=0.1)
abline(h=0, lty=3)

plot(tt,betas[4,], xlab= "Quantile,t", ylab="beta(t)",main="non-Hispanic White",cex=0.1)
points(tt, beta_lcl[4,], col="red", cex=0.1)
points(tt, beta_ucl[4,], col="green", cex=0.1)
abline(h=0, lty=3)

plot(tt,betas[5,], xlab= "Quantile,t", ylab="beta(t)",main="non-Hispanic black",cex=0.1)
points(tt, beta_lcl[5,], col="red", cex=0.1)
points(tt, beta_ucl[5,], col="green", cex=0.1)
abline(h=0, lty=3)

plot(tt,betas[6,], xlab= "Quantile,t", ylab="beta(t)",main="non-Hispanic Asian",cex=0.1)
points(tt, beta_lcl[6,], col="red", cex=0.1)
points(tt, beta_ucl[6,], col="green", cex=0.1)
abline(h=0, lty=3)

plot(tt,betas[7,], xlab= "Quantile,t", ylab="beta(t)",main="non-Hispanic multiracial",cex=0.1)
points(tt, beta_lcl[7,], col="red", cex=0.1)
points(tt, beta_ucl[7,], col="green", cex=0.1)
abline(h=0, lty=3)

plot(tt,betas[8,], xlab= "Quantile,t", ylab="beta(t)",cex=0.1, main="BMXWAIST")
points(tt, beta_lcl[8,], col="red", cex=0.1)
points(tt, beta_ucl[8,], col="green", cex=0.1)
abline(h=0, lty=3)

plot(tt,betas[9,],main= rnames[9], xlab= "Quantile,t", ylab="beta(t)",cex=0.1, main="HEI")
points(tt, betas_lcl[9,], col="red", cex=0.1)
points(tt, betas_ucl[9,], col="green", cex=0.1)
abline(h=0, lty=3)

```

